Repository codestates-seb/seb44_main_017, pull requests merged in 2023-07, with the labels that each got.

#15 [feat] 햄버거 메뉴바, 헤더 프로필 적용
  client/index.html
  client/src/App.tsx
  client/src/assets/askQuestion.svg
  client/src/assets/clothes.svg
  client/src/assets/icons/Closed.tsx
  client/src/assets/icons/Hamburger.tsx
  client/src/assets/icons/Logout.tsx
  client/src/assets/logout-svgrepo-com (2).svg
  client/src/assets/magnifier.svg
  client/src/assets/notice.svg
  client/src/assets/product.svg
  client/src/assets/react.svg
  client/src/components/Dropdown_hamburger/Backdrop.tsx
  client/src/components/Dropdown_hamburger/HamburgerDropdown.tsx
  client/src/components/Dropdown_hamburger/style.ts
  client/src/components/Dropdown_profile/ProfileDropdown.tsx
  client/src/components/Dropdown_profile/style.ts
  client/src/components/Header/Header.tsx
  client/src/components/Header/header.css
  client/src/hooks/useDetectClose.ts
  client/src/types/SvgTagProps.ts
Labels: ❤ FE, ✔ FEAT

#17 [feat] 정렬용 select box 컴포넌트 구현
  client/src/assets/icons/SelectArrow.tsx
  client/src/assets/logout-svgrepo-com (2).svg
  client/src/components/SelectBox/SelectBox.tsx
  client/src/components/SelectBox/style.ts
Labels: ❤ FE, ✔ FEAT

#24 [feat] 댓글 컴포넌트 기초 구현
  client/src/assets/icons/DeleteButton.tsx
  client/src/assets/icons/EditButton.tsx
  client/src/components/Comment/Comment.tsx
  client/src/components/Comment/style.ts
  client/src/hooks/useInput.ts
  client/src/moks/comment.json
  client/src/utils/elapsedTime.tsx
Labels: ❤ FE, ✔ FEAT

#26 [refactor] 댓글 경과시간 로직 수정, 사이드바 CSS 조정
  client/src/components/Comment/Comment.tsx
  client/src/components/Dropdown_hamburger/HamburgerDropdown.tsx
  client/src/components/Dropdown_hamburger/style.ts
  client/src/moks/comment.json
  client/src/utils/elapsedTime.tsx
Labels: ❤ FE, ⛏ FIX

#55 [feat] 의류 수거 요청 페이지 작업
  client/src/components/Collection_form/CollectionForm.tsx
  client/src/components/Collection_form/style.ts
  client/src/components/SelectBox/SelectBox.tsx
  client/src/components/SelectBox/style.ts
  client/src/constants/constants.tsx
  client/src/pages/collectionPage/collectionPage.tsx
  client/src/pages/collectionPage/style.ts
Labels: ❤ FE, ✔ FEAT

#66 [feat] QnA 목록 페이지 작업
  client/src/App.tsx
  client/src/assets/icons/SelectArrow.tsx
  client/src/components/Collection_form/CollectionForm.tsx
  client/src/components/Comment/Comment.tsx
  client/src/components/Dropdown_hamburger/HamburgerDropdown.tsx
  client/src/components/Header/Header.tsx
  client/src/components/SelectBox/SelectBox.tsx
  client/src/components/SelectBox/style.ts
  client/src/hooks/useInput.ts
  client/src/pages/collectionPage/collectionPage.tsx
  client/src/pages/qnaListPage/qnaListPage.tsx
  client/src/pages/qnaListPage/style.ts
  client/src/types/shared.ts
Labels: ❤ FE, ✔ FEAT

#75 [feat] QnA 관련 페이지, ScrollTop 유틸 함수 작업
  client/src/App.tsx
  client/src/assets/icons/ViewCount.tsx
  client/src/components/BoardDetail/BoardDetail.tsx
  client/src/components/BoardDetail/style.ts
  client/src/components/Comment/Comment.tsx
  client/src/components/Comment/style.ts
  client/src/components/SelectBox/SelectBox.tsx
  client/src/pages/qnaDetailPage/qnaDetailPage.tsx
  client/src/pages/qnaListPage/qnaListPage.tsx
  client/src/pages/qnaListPage/style.ts
  client/src/types/shared.ts
  client/src/utils/scrollTop.tsx
Labels: ❤ FE, ✔ FEAT, ⛏ FIX

#76 [refactor] scrollTop 유틸 함수 위치 수정(app.tsx -> main.tsx)
  client/src/App.tsx
  client/src/main.tsx
Labels: ❤ FE, ⛏ FIX

#81 [design] 댓글 컴포넌트 API 작업 및 QnA 리스트, 상세 페이지, 댓글 컴포넌트 레이아웃 수정
  client/src/components/BoardDetail/BoardDetail.tsx
  client/src/components/BoardDetail/style.ts
  client/src/components/Comment/Comment.tsx
  client/src/components/Comment/style.ts
  client/src/components/SelectBox/SelectBox.tsx
  client/src/components/SelectBox/style.ts
  client/src/pages/qnaDetailPage/qnaDetailPage.tsx
  client/src/pages/qnaListPage/qnaListPage.tsx
  client/src/pages/qnaListPage/style.ts
  client/src/types/shared.ts
Labels: ❤ FE, ⛏ FIX

#97 feat: 상품리스트 페이지 구현
  client/src/components/CategoryButton/CategoryButton.tsx
  client/src/pages/productListPage/productListPage.tsx
  client/src/pages/productListPage/style.tsx
Labels: ❤ FE, ✔ FEAT

#99 [feat] mypage 상품 관리 페이지 작업 및 셀렉트 박스 유형 추가
  client/src/App.tsx
  client/src/assets/icons/PointIcon.tsx
  client/src/assets/icons/default_image.png
  client/src/components/Mypage_header/MypageHeader.tsx
  client/src/components/Mypage_header/style.ts
  client/src/components/SelectBox/SelectBox.tsx
  client/src/components/SelectBox/style.ts
  client/src/pages/mypage/mypage.tsx
  client/src/pages/myproductsPage/myproductsPage.tsx
  client/src/pages/myproductsPage/style.ts
  client/src/types/shared.ts
Labels: ❤ FE, ✔ FEAT

#122 [feat] 검색 컴포넌트 작업
  client/src/assets/icons/SearchIcon.tsx
  client/src/components/Collection_form/style.ts
  client/src/components/Modal_login/LoginModal.tsx
  client/src/components/Qna_list/qnaListComponent.tsx
  client/src/components/Search_bar/SearchBar.tsx
  client/src/pages/collectionPage/collectionPage.tsx
  client/src/pages/myQnaPage/myQnaPage.tsx
  client/src/pages/qnaListPage/qnaListPage.tsx
Labels: ❤ FE, ✔ FEAT

#126 [refactor] 로그인, 비로그인 / 사용자, 관리자 조건부 렌더링 작업
  client/src/assets/icons/Logout.tsx
  client/src/components/Comment/Comment.tsx
  client/src/components/Dropdown_hamburger/HamburgerDropdown.tsx
  client/src/components/Dropdown_hamburger/style.ts
  client/src/components/Dropdown_profile/ProfileDropdown.tsx
  client/src/components/SelectBox/style.ts
  client/src/types/shared.ts
  client/src/utils/token.tsx
Labels: ❤ FE, ⛏ FIX

#143 [feat] 장바구니 페이지 작업
  client/src/assets/icons/PointIcon.tsx
  client/src/components/Dropdown_profile/ProfileDropdown.tsx
  client/src/components/Item_product/ProductItem.tsx
  client/src/components/Mypage_header/MypageHeader.tsx
  client/src/constants/constants.tsx
  client/src/pages/myproductsPage/myproductsPage.tsx
  client/src/pages/shoppingCartPage/shoppingCartPage.tsx
  client/src/pages/shoppingCartPage/style.ts
  client/src/recoil/atom.ts
  client/src/types/shared.ts
Labels: ❤ FE, ✔ FEAT

#145 [refactor] Comment 컴포넌트 QnA와 Product에서 재사용되도록 리팩토링
  client/src/components/Comment/Comment.tsx
  client/src/components/Dropdown_hamburger/HamburgerDropdown.tsx
  client/src/pages/qnaDetailPage/qnaDetailPage.tsx
  client/src/types/shared.ts
Labels: ❤ FE, ⛏ FIX

#171 [feat] 장바구니 페이지 완성 및 사이드바, 드롭다운 CSS 수정 작업
  client/src/assets/icons/CartIcon.tsx
  client/src/assets/managerIcon.svg
  client/src/components/ApprovalTable/ApprovalTable.tsx
  client/src/components/BoardDetail/style.ts
  client/src/components/Comment/Comment.tsx
  client/src/components/Dropdown_hamburger/HamburgerDropdown.tsx
  client/src/components/Dropdown_hamburger/style.ts
  client/src/components/Dropdown_profile/ProfileDropdown.tsx
  client/src/components/Dropdown_profile/style.ts
  client/src/components/Item_product/ProductItem.tsx
  client/src/pages/collectionPage/style.ts
  client/src/pages/noticeDetailPage/noticeDetailPage.tsx
  client/src/pages/noticeDetailPage/style.tsx
  client/src/pages/productInfoPage/ProductInfo.tsx
  client/src/pages/productInfoPage/productInfoPage.tsx
  client/src/pages/productInfoPage/style.ts
  client/src/pages/shoppingCartPage/shoppingCartPage.tsx
  client/src/pages/shoppingCartPage/style.ts
  client/src/recoil/atom.ts
  client/src/types/shared.ts
  client/src/utils/elapsedTime.tsx
Labels: ❤ FE, ✔ FEAT, ⛏ FIX

#181 [design] QnA 목록, 마이페이지, 셀렉트 박스, 의류 수거 신청 페이지 등 UI 수정 작업
  client/src/components/Collection_form/style.ts
  client/src/components/Comment/Comment.tsx
  client/src/components/Comment/style.ts
  client/src/components/Dropdown_profile/style.ts
  client/src/components/Mypage_header/style.ts
  client/src/components/Qna_list/qnaListComponent.tsx
  client/src/components/Qna_list/style.ts
  client/src/components/SelectBox/style.ts
  client/src/pages/collectionPage/collectionPage.tsx
  client/src/pages/collectionPage/style.ts
  client/src/pages/myproductsPage/myproductsPage.tsx
  client/src/pages/myproductsPage/style.ts
  client/src/pages/qnaListPage/qnaListPage.tsx
Labels: ❤ FE, ⛏ FIX

#182 [design] 상품 상세 페이지 및 코멘트 UI 수정 작업
  client/src/components/Comment/style.ts
  client/src/pages/productInfoPage/ProductInfo.tsx
  client/src/pages/productInfoPage/productInfoPage.tsx
  client/src/pages/productInfoPage/style.ts
  client/src/pages/productListPage/productListPage.tsx
Labels: ❤ FE, ⛏ FIX

#196 [fix] 드롭다운 위치, 사이드바 메뉴, 마이페이지 UI 수정
  client/src/components/Dropdown_hamburger/HamburgerDropdown.tsx
  client/src/components/Dropdown_profile/ProfileDropdown.tsx
  client/src/components/Dropdown_profile/style.ts
  client/src/components/Mypage_header/style.ts
  client/src/components/Qna_list/style.ts
  client/src/pages/myproductsPage/style.ts
  client/src/pages/shoppingCartPage/style.ts
Labels: ❤ FE, ⛏ FIX

#197 [fix] 상품 상세 페이지 코멘트 수정 관련 에러, 장바구니 페이지 조건부 CSS 작업
  client/src/components/Comment/Comment.tsx
  client/src/pages/shoppingCartPage/shoppingCartPage.tsx
  client/src/pages/shoppingCartPage/style.ts
Labels: ❤ FE, ⛏ FIX

#200 [feat] 장바구니 결제 주소 입력 및 request 기능 구현
  client/package-lock.json
  client/package.json
  client/src/components/Comment/Comment.tsx
  client/src/components/Postcode/Postcode.tsx
  client/src/pages/qnaDetailPage/qnaDetailPage.tsx
  client/src/pages/shoppingCartPage/shoppingCartPage.tsx
  client/src/pages/shoppingCartPage/style.ts
  client/src/types/shared.ts
Labels: ❤ FE, ✔ FEAT

#201 [refactor] 커스텀 알림창 제작 & 반영
  client/src/components/Comment/Comment.tsx
  client/src/components/Mypage_header/style.ts
  client/src/components/Postcode/Postcode.tsx
  client/src/components/SubTItleBar/styled.ts
  client/src/pages/myproductsPage/style.ts
  client/src/pages/qnaDetailPage/qnaDetailPage.tsx
  client/src/pages/qnaListPage/qnaListPage.tsx
  client/src/utils/customConfirm.tsx
  client/src/utils/customPrompt.tsx
Labels: ❤ FE, ✔ FEAT

#217 [refactor] 장바구니 페이지 로직 변경
  client/src/App.tsx
  client/src/components/Dropdown_hamburger/HamburgerDropdown.tsx
  client/src/components/Dropdown_profile/ProfileDropdown.tsx
  client/src/components/Dropdown_profile/style.ts
  client/src/components/Mypage_header/style.ts
  client/src/pages/noticeModifyPage/noticeModifyPage.tsx
  client/src/pages/productInfoPage/style.ts
  client/src/pages/shoppingCartPage/shoppingCartPage.tsx
  client/src/pages/shoppingCartPage/style.ts
  client/src/types/shared.ts
Labels: ❤ FE, ⛏ FIX

#223 [fix] 상품 상세페이지 로그인/비로그인 둘 다 가능하도록 수정, 코멘트 관련 버그 수정
  client/src/components/Comment/Comment.tsx
  client/src/pages/productInfoPage/ProductInfo.tsx
  client/src/pages/productInfoPage/productInfoPage.tsx
  client/src/pages/productInfoPage/style.ts
Labels: ❤ FE, ⛏ FIX

#239 [fix] 사이드바, 드롭다운 메뉴 변경, 검색 관련 로직 수정
  client/src/assets/icons/SearchIcon.tsx
  client/src/components/BoardDetail/style.ts
  client/src/components/Dropdown_hamburger/HamburgerDropdown.tsx
  client/src/components/Dropdown_profile/ProfileDropdown.tsx
  client/src/components/Qna_list/qnaListComponent.tsx
  client/src/components/Search_bar/SearchBar.tsx
  client/src/pages/productListPage/productListPage.tsx
Labels: ❤ FE, ⛏ FIX

#250 [fix] 장바구니 및 구매하기 후 navigate 추가
  client/src/components/Postcode/Postcode.tsx
  client/src/components/Qna_list/style.ts
  client/src/hooks/useDebounce.ts
  client/src/pages/productInfoPage/productInfoPage.tsx
  client/src/pages/shoppingCartPage/shoppingCartPage.tsx
Labels: ❤ FE, ✔ FEAT

#251 [feat] 내가 구매한 물품 마이페이지에서 확인할 수 있도록 수정
  client/src/components/Mypage_header/style.ts
  client/src/components/Qna_list/style.ts
  client/src/components/SelectBox/SelectBox.tsx
  client/src/pages/myproductsPage/myproductsPage.tsx
  client/src/pages/myproductsPage/style.ts
Labels: ❤ FE, ✔ FEAT

#254 [fix] 로그아웃 비동기 관련 작업
  client/src/components/Comment/Comment.tsx
  client/src/components/Dropdown_hamburger/HamburgerDropdown.tsx
  client/src/components/Dropdown_profile/ProfileDropdown.tsx
  client/src/pages/myproductsPage/myproductsPage.tsx
  client/src/pages/shoppingCartPage/style.ts
  client/src/utils/token.tsx
Labels: ❤ FE, ⛏ FIX

#256 [fix] 상품 상세 페이지 반응형 작업 및 버그 수정
  client/package.json
  client/src/components/Comment/Comment.tsx
  client/src/components/Qna_list/qnaListComponent.tsx
  client/src/pages/noticePage/noticePage.tsx
  client/src/pages/productInfoPage/ProductInfo.tsx
  client/src/pages/productInfoPage/productInfoPage.tsx
  client/src/pages/productInfoPage/style.ts
  client/src/pages/productListPage/productListPage.tsx
Labels: ❤ FE, ⛏ FIX
